version: "3.9"

services:
  # === GATEWAY SERVICE ===
  gateway:
    build: ./gateway
    container_name: ecommerce-gateway
    ports:
      - "8000:8000"           # Host:Gateway port
    env_file:
      - ./gateway/.env        # SERVICE_ANALITICA burada olacaq
    volumes:
      - ./gateway:/app
    depends_on:
      - analytic
    networks:
      - ecommerce_net
    restart: always

  # === ANALITIC SERVICE ===
  analytic:
    build: ./analytic
    container_name: ecommerce-analytic
    ports:
      - "8080:8000"           # Host:Container port mapping (Django default 8000)
    env_file:
      - ./analytic/.env
    volumes:
      - ./analytic:/app
    networks:
      - ecommerce_net
    restart: always

networks:
  ecommerce_net:
    driver: bridge
