version: "3.9"

services:
  # === GATEWAY SERVICE ===
  gateway:
    build: ./gateway       # Projects içindəki submodule qovluğu
    container_name: ecommerce-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
    depends_on:
      - analytic
    networks:
      - ecommerce_net
    restart: always

  # === ANALITIC SERVICE ===
  analytic:
    build: ./analytic      # Projects içindəki submodule qovluğu
    container_name: ecommerce-analytic
    ports:
      - "8080:8000"
    env_file:
      - ./analytic/.env
    volumes:
      - ./analytic:/app
    networks:
      - ecommerce_net
    restart: always

networks:
  ecommerce_net:
    driver: bridge
